name: wmm_cof_example
description: Example use of the wmm_cof package.
version: 1.0.0

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  wmm_cof:
    path: ../
  resource:

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
